# Generated by Django 3.2.11 on 2024-01-18 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guardian",
            options={
                "ordering": ["-created_at", "last_name", "first_name"],
                "verbose_name": "guardian",
                "verbose_name_plural": "guardians",
            },
        ),
    ]
