# Generated by Django 3.2.11 on 2024-05-24 11:27

from django.db import migrations, models


def init_communication_accepted_for_existing_guardians(apps, schema_editor):
    Guardian = apps.get_model("users", "Guardian")
    Guardian.objects.all().update(has_accepted_communication=True)


class Migration(migrations.Migration):
    """
    The `has_accepted_marketing` field was named badly,
    since there is "no marketing messaging of any kind" in Kukkuu.
    However, there is a need for a field that tells whether or not
    a user allows messaging, like email sending, related to event
    invitations, etc. The users has implicitly accepted communication
    when they have created an account to the Kukkuu service.

    The `has_accepted_marketing` has not yet been
    in use for long. It's been implemented because of auth service
    change and no decisions have been made earlier that could not
    be overridden now, when the Kukkuu is changing the auth service
    from Tunnistamo to Keycloak (Helsinki-profile). Because of that,
    the `has_accepted_marketing` field values can be ignored and
    all the `has_accepted_communication` can be set to True for
    all the existing rows in db.
    """

    dependencies = [
        ("users", "0012_user_is_obsolete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guardian",
            name="has_accepted_marketing",
        ),
        migrations.AddField(
            model_name="guardian",
            name="has_accepted_communication",
            field=models.BooleanField(
                default=False, verbose_name="accepts communication"
            ),
        ),
        migrations.RunPython(init_communication_accepted_for_existing_guardians),
    ]
