# Generated by Django 4.2.21 on 2025-05-23 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_deactivate_obsolete_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_obsolete",
        ),
    ]
