# Generated by Django 5.2.17 on 2026-10-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0001_initial"),
        ("users", "0016_user_last_api_use"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organisations",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="organisations.organisation",
                verbose_name="organisations",
            ),
        ),
    ]
