# Generated by Django 2.2.9 on 2020-01-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_delete_old_duration_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="int_duration", new_name="duration",
        ),
    ]
