# Generated by Django 2.2.13 on 2021-06-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_change_enrolment_child_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ticket_system",
            field=models.CharField(
                choices=[("internal", "Internal"), ("ticketmaster", "Ticketmaster")],
                default="internal",
                max_length=32,
                verbose_name="ticket system",
            ),
        ),
    ]
