# Generated by Django 2.2.13 on 2021-06-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_add_event_ticket_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrence",
            name="ticket_system_url",
            field=models.URLField(blank=True, verbose_name="ticket system URL"),
        ),
    ]
