# Generated by Django 3.2.8 on 2021-10-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0022_add_ticket_system_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrolment",
            name="attended",
            field=models.BooleanField(blank=True, null=True, verbose_name="attended"),
        ),
    ]
