# Generated by Django 3.2.8 on 2021-12-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0023_alter_enrolment_attended"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolment",
            name="feedback_notification_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="feedback notification sent at"
            ),
        ),
    ]
