# Generated by Django 3.2.11 on 2022-03-10 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0024_add_enrolment_feedback_notification_sent_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrolment",
            options={
                "ordering": ("id",),
                "verbose_name": "enrolment",
                "verbose_name_plural": "enrolments",
            },
        ),
    ]
