# Generated by Django 3.2.11 on 2022-10-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0026_add_event_ticket_system_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ticket_system_end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="ticket system end time"
            ),
        ),
    ]
