# Generated by Django 3.2.11 on 2023-05-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0027_add_event_ticket_system_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="ticket_system",
            field=models.CharField(
                choices=[
                    ("internal", "Internal"),
                    ("ticketmaster", "Ticketmaster"),
                    ("lippupiste", "Lippupiste"),
                ],
                default="internal",
                max_length=32,
                verbose_name="ticket system",
            ),
        ),
    ]
