# Generated by Django 3.2.11 on 2023-12-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0028_alter_event_ticket_system"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["created_at", "id"],
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
    ]
