# Generated by Django 4.2.14 on 2024-10-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0029_alter_event_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="ticket_system",
            field=models.CharField(
                choices=[
                    ("internal", "Internal"),
                    ("ticketmaster", "Ticketmaster"),
                    ("lippupiste", "Lippupiste"),
                    ("tixly", "Tixly"),
                ],
                default="internal",
                max_length=32,
                verbose_name="ticket system",
            ),
        ),
    ]
