# Generated by Django 5.2.17 on 2026-10-09 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0030_add_tixly_ticket_system"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="organisation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="organisations.organisation",
                verbose_name="organisation",
            ),
        ),
    ]
