# Generated by Django 5.2.17 on 2026-10-09 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0032_populate_event_organisation"),
        ("organisations", "0002_create_default_organisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="organisations.organisation",
                verbose_name="organisation",
            ),
        ),
    ]
