# Generated by Django 2.2.13 on 2021-02-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_add_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="single_events_allowed",
            field=models.BooleanField(
                default=True,
                help_text="Whether it is allowed to create events outside event groups.",
                verbose_name="single events allowed",
            ),
        ),
    ]
