# Generated by Django 2.2.13 on 2021-02-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_add_single_events_allowed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["year"],
                "permissions": (
                    ("admin", "Base admin permission"),
                    ("publish", "Can publish events and event groups"),
                    (
                        "manage_event_groups",
                        "Can create, update and delete event groups",
                    ),
                ),
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
    ]
