# Generated by Django 4.2.17 on 2025-01-20 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_add_projects_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "default_permissions": [],
                "ordering": ["year"],
                "permissions": (
                    ("admin", "Base admin permission"),
                    ("publish", "Can publish events and event groups"),
                    (
                        "manage_event_groups",
                        "Can create, update and delete event groups",
                    ),
                    (
                        "can_send_to_all_in_project",
                        "Can send messages to all recipients in project",
                    ),
                    ("view_families", "Can view families"),
                ),
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
    ]
