services:
    postgres:
        image: postgres:17
        restart: on-failure
        env_file:
            - .env  # For POSTGRES_USER, POSTGRES_PASSWORD and POSTGRES_DB
        ports:
            - 5434:5432
        volumes:
          - pgdata:/var/lib/postgresql/data
        container_name: kukkuu-db

    django:
        build:
            context: .
            target: ${DOCKER_TARGET:-development}  # stage of Dockerfile to build
        env_file:
            - .env
        volumes:
            - .:/app
        ports:
            - 8081:8081
            - 8000:8000
        depends_on:
            - postgres
        container_name: kukkuu-backend

volumes:
    pgdata:
        driver: local

networks:
    default:
        name: helsinki
