services:
    postgres:
        image: postgres:13
        restart: on-failure
        environment:
            POSTGRES_USER: kukkuu
            POSTGRES_PASSWORD: kukkuu
            POSTGRES_DB: kukkuu
        ports:
            - 5434:5432
        volumes:
          - pgdata:/var/lib/postgresql@13/data
        container_name: kukkuu-db

    django:
        build:
            context: .
            target: ${DOCKER_TARGET:-development}
        env_file:
            - docker-compose.env
        environment:
            DATABASE_URL: postgres://kukkuu:kukkuu@kukkuu-db/kukkuu
            DATABASE_HOST: kukkuu-db.helsinki
            SKIP_DATABASE_CHECK: 1
        volumes:
            - .:/app
        ports:
            - 8081:8081
            - 8000:8000
        depends_on:
            - postgres
        container_name: kukkuu-backend

volumes:
    pgdata:
        driver: local

networks:
    default:
        name: helsinki
