# Common errors
from django.conf import settings

DEFAULT_LANGUAGE = settings.LANGUAGES[0][0]

GENERAL_ERROR = "GENERAL_ERROR"
PERMISSION_DENIED_ERROR = "PERMISSION_DENIED_ERROR"
OBJECT_DOES_NOT_EXIST_ERROR = "OBJECT_DOES_NOT_EXIST_ERROR"
DATA_VALIDATION_ERROR = "DATA_VALIDATION_ERROR"
API_USAGE_ERROR = "API_USAGE_ERROR"

# Kukkuu specific errors
MAX_NUMBER_OF_CHILDREN_PER_GUARDIAN_ERROR = "MAX_NUMBER_OF_CHILDREN_PER_GUARDIAN_ERROR"
CHILD_ALREADY_JOINED_EVENT_ERROR = "CHILD_ALREADY_JOINED_EVENT_ERROR"
PAST_OCCURRENCE_ERROR = "PAST_OCCURRENCE_ERROR"
OCCURRENCE_IS_FULL_ERROR = "OCCURRENCE_IS_FULL_ERROR"
OCCURRENCE_MISMATCH_ERROR = "OCCURRENCE_MISMATCH_ERROR"
EVENT_ALREADY_PUBLISHED_ERROR = "EVENT_ALREADY_PUBLISHED_ERROR"
EVENT_GROUP_ALREADY_PUBLISHED_ERROR = "EVENT_GROUP_ALREADY_PUBLISHED_ERROR"
EVENT_GROUP_NOT_READY_FOR_PUBLISHING_ERROR = (
    "EVENT_GROUP_NOT_READY_FOR_PUBLISHING_ERROR"
)
EVENT_NOT_PUBLISHED_ERROR = "EVENT_NOT_PUBLISHED_ERROR"
MISSING_DEFAULT_TRANSLATION_ERROR = "MISSING_DEFAULT_TRANSLATION_ERROR"
INELIGIBLE_OCCURRENCE_ENROLMENT = "INELIGIBLE_OCCURRENCE_ENROLMENT"
INVALID_EMAIL_FORMAT_ERROR = "INVALID_EMAIL_FORMAT_ERROR"
ALREADY_SUBSCRIBED_ERROR = "ALREADY_SUBSCRIBED_ERROR"
OCCURRENCE_IS_NOT_FULL_ERROR = "OCCURRENCE_IS_NOT_FULL_ERROR"
MESSAGE_ALREADY_SENT_ERROR = "MESSAGE_ALREADY_SENT_ERROR"
PAST_ENROLMENT_ERROR = "PAST_ENROLMENT_ERROR"
SINGLE_EVENTS_DISALLOWED_ERROR = "SINGLE_EVENTS_DISALLOWED_ERROR"
TICKET_SYSTEM_URL_MISSING_ERROR = "TICKET_SYSTEM_URL_MISSING_ERROR"
NO_FREE_TICKET_SYSTEM_PASSWORDS_ERROR = "NO_FREE_TICKET_SYSTEM_PASSWORDS_ERROR"
TICKET_SYSTEM_PASSWORD_NOTHING_TO_IMPORT_ERROR = (
    "TICKET_SYSTEM_PASSWORD_NOTHING_TO_IMPORT_ERROR"
)
TICKET_SYSTEM_PASSWORD_ALREADY_ASSIGNED_ERROR = (
    "TICKET_SYSTEM_PASSWORD_ALREADY_ASSIGNED_ERROR"
)
UNAUTHENTICATED_ERROR = "UNAUTHENTICATED_ERROR"
AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
AUTHENTICATION_EXPIRED_ERROR = "AUTHENTICATION_EXPIRED_ERROR"
VERIFICATION_TOKEN_INVALID_ERROR = "VERIFICATION_TOKEN_INVALID_ERROR"
