# Generated by Django 3.2.11 on 2023-12-13 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("children", "0006_add_languages_spoken_at_home"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="child",
            options={
                "ordering": ["birthdate", "last_name", "first_name"],
                "verbose_name": "child",
                "verbose_name_plural": "children",
            },
        ),
    ]
