# Generated by Django 3.2.11 on 2024-01-18 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("children", "0007_alter_child_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relationship",
            options={
                "ordering": ["guardian", "child"],
                "verbose_name": "relationship",
                "verbose_name_plural": "relationships",
            },
        ),
    ]
