# Generated by Django 3.2.11 on 2024-01-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("children", "0010_rename_child_first_name_to_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="child",
            options={
                "ordering": ["birthyear", "name"],
                "verbose_name": "child",
                "verbose_name_plural": "children",
            },
        ),
        migrations.RenameField(
            model_name="child",
            old_name="birthdate",
            new_name="birthyear",
        ),
        migrations.AlterField(
            model_name="child",
            name="birthyear",
            field=models.DateField(verbose_name="birthyear"),
        ),
    ]
