# Generated by Django 3.2.11 on 2024-01-19 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("children", "0011_child_birthdate_to_birthyear"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE children_child ALTER birthyear TYPE INTEGER USING EXTRACT(year FROM birthyear)"
        )
    ]
