# Generated by Django 3.2.11 on 2024-02-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("children", "0012_child_birthyear_to_integer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="birthyear",
            field=models.IntegerField(verbose_name="birthyear"),
        ),
    ]
