# Generated by Django 3.2.11 on 2024-05-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("children", "0013_alter_child_birthyear"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="notes"),
        ),
    ]
