#
# Review pipeline. Run build and deploy for Platta dev environments.
# Pipeline runs different tests e.g. unittest and browser tests.
#
# Continuous integration (CI) triggers cause a pipeline to run whenever you push
# an update to the specified branches or you push specified tags.
# only PR trigger pipeline
trigger: none

# Pull request (PR) triggers cause a pipeline to run whenever a pull request is
# opened with one of the specified target branches, or when updates are made to 
# such a pull request.
#
# GitHub creates a new ref when a pull request is created. The ref points to a 
# merge commit, which is the merged code between the source and target branches 
# of the pull request.
#
# Opt out of pull request validation 
pr:
  # PR target branch
  branches:
    include:
    - master
  paths:
    exclude:
    - '*release-please*'
    - '**/*.md'
    - '.github/'
    - 'pipelines/kukkuu-api-release.yml'
    - 'pipelines/kukkuu-api-dev.yml'
    - 'docker-compose*'
    - 'compose.*'

# By default, use self-hosted agents
pool: Default

resources:
  repositories:
    # Azure DevOps repository
    - repository: kukkuu-pipelines
      type: git
      ref: refs/heads/ansible_automation_update
      # Azure DevOps project/repository
      name: kukkuu/kukkuu-pipelines

extends:
  # Filename in Azure DevOps Repository
  template: components/kukkuu-api/pipelines/kukkuu-api-review.yml@kukkuu-pipelines
  parameters:
    # Application build arguments and config map values as key value pairs.
    # Does not contain all buildArguments or configMap values, the rest located in kukkuu-pipelines
    # The values here will override the values defined in the kukkuu-pipelines repository
    # buildArgs:
    configMap: # pod environment variables
      DEBUG: 1
      ADD_DEFAULT_LANGUAGES: 1
      TOKEN_AUTH_BROWSER_TEST_ENABLED: 1
      TOKEN_AUTH_BROWSER_TEST_JWT_ISSUER: https://kukkuu-ui.test.hel.ninja,https://kukkuu-admin.test.hel.ninja
