# Generated by Django 4.2.14 on 2024-10-14 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_ilmoitin', '0005_bigauto_pk_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='admins_to_notify',
            field=models.ManyToManyField(
                blank=True, 
                help_text='Choose admin users you want to be notified when this event happens.', 
                # the related name has changed from 0002_add_admin_notifications.py, where it was:
                # related_name="_notificationtemplate_admins_to_notify_+"
                related_name='+',
                to=settings.AUTH_USER_MODEL, 
                verbose_name='Admins to notify'),
        ),
        # The `notificationtemplatetranslation` id field type has changed from 0001_initial.py, 
        # where it was AutoField. Now it is BigAutoField, since a change introduced in
        # https://github.com/City-of-Helsinki/django-ilmoitin/pull/34 
        # (commit: https://github.com/City-of-Helsinki/django-ilmoitin/pull/34/commits/66eb7f02621013143a11de4a6b046e6eef43c5ca). # noqa
        migrations.AlterField(
            model_name='notificationtemplatetranslation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
