name: Build & Production
on:
  push:
    tags:
      - 'release-*'

# allow only one run at a time
concurrency: ${{ github.workflow }}

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STABLE }}
  BASE_DOMAIN: ${{ secrets.BASE_DOMAIN_STABLE }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  APP_MIGRATE_COMMAND: /app/.prod/on_deploy.sh
  K8S_REQUEST_CPU: 100m
  K8S_REQUEST_RAM: 400Mi
  K8S_LIMIT_CPU: 800m
  K8S_LIMIT_RAM: 800Mi
  # horizontal pod autoscaler
  K8S_HPA_ENABLED: true
  K8S_HPA_MAX_REPLICAS: 8
  K8S_HPA_MIN_REPLICAS: 2
  K8S_HPA_MAX_CPU_AVG: 80 # 80% from request
#  K8S_HPA_MAX_RAM_AVG: 80 # 80% from request

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andersinno/kolga-build-action@v2

  production:
    runs-on: ubuntu-latest
    needs: build
    name: Production
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: 'stable'
        env:
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STABLE }}
          ENVIRONMENT_URL: https://${{ secrets.ENVIRONMENT_URL_STABLE }}
          K8S_SECRET_DEBUG: 0
          K8S_SECRET_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY_STABLE }}
          K8S_SECRET_ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS_STABLE }}
          K8S_SECRET_CORS_ORIGIN_ALLOW_ALL: 1
          K8S_SECRET_SKIP_DATABASE_CHECK: 1
          K8S_SECRET_USE_X_FORWARDED_HOST: 1
          K8S_SECRET_TOKEN_AUTH_ACCEPTED_AUDIENCE: "https://api.hel.fi/auth/kukkuuapiprod"
          K8S_SECRET_TOKEN_AUTH_REQUIRE_SCOPE_PREFIX: 0
          K8S_SECRET_TOKEN_AUTH_AUTHSERVER_URL: "https://api.hel.fi/sso/openid"
          K8S_SECRET_ILMOITIN_QUEUE_NOTIFICATIONS: 1
          K8S_SECRET_MAIL_MAILGUN_KEY: ${{ secrets.GH_STABLE_MAILGUN_API_KEY }}
          K8S_SECRET_MAIL_MAILGUN_DOMAIN: "hel.fi"
          K8S_SECRET_MAIL_MAILGUN_API: "https://api.eu.mailgun.net/v3"
          K8S_SECRET_MAILER_EMAIL_BACKEND: "anymail.backends.mailgun.EmailBackend"
          K8S_SECRET_DEFAULT_FROM_EMAIL: "Kulttuurin kummilapset <noreply@hel.fi>"
          K8S_SECRET_ILMOITIN_TRANSLATED_FROM_EMAIL: "fi=Kulttuurin kummilapset <noreply@hel.fi>,en=Culture Kids <noreply@hel.fi>,sv=Kulturens fadderbarn <noreply@hel.fi>"
          # Message sender. International numbers with + or 00 prefix
          # and 5 to 15 numbers following it, national ones / shortcodes
          # with 1 to 15 numbers, alphanumeric with max 11 characters.
          # https://quriiri.fi/wp-content/uploads/2022/03/Quriiri-HTTP-MT-API-v1.pdf
          # K8S_SECRET_TRANSLATED_SMS_SENDER: "fi=Kulttuurin kummilapset,en=Culture Kids,sv=Kulturens fadderbarn"
          K8S_SECRET_NOTIFICATION_SERVICE_API_TOKEN: ${{ secrets.GH_NS_API_TOKEN_STABLE }}
          K8S_SECRET_NOTIFICATION_SERVICE_API_URL: ${{ secrets.GH_NS_API_URL_STABLE }}
          K8S_SECRET_DEFAULT_FILE_STORAGE: "storages.backends.azure_storage.AzureStorage"
          K8S_SECRET_AZURE_ACCOUNT_NAME: ${{ secrets.AZURE_ACCOUNT_NAME }}
          K8S_SECRET_AZURE_ACCOUNT_KEY: ${{ secrets.AZURE_ACCOUNT_KEY }}
          K8S_SECRET_AZURE_CONTAINER: ${{ secrets.AZURE_CONTAINER }}
          K8S_SECRET_SENTRY_DSN: ${{ secrets.GH_SENTRY_DSN }}
          K8S_SECRET_SENTRY_ENVIRONMENT: "kukkuu-production"
          K8S_SECRET_DATABASE_HOST: ${{ secrets.K8S_SECRET_DATABASE_HOST_STABLE }}
          K8S_SECRET_DATABASE_URL: ${{ secrets.K8S_SECRET_DATABASE_URL_STABLE }}
          K8S_SECRET_DATABASE_PORT: ${{ secrets.K8S_SECRET_DATABASE_PORT_STABLE }}
          K8S_SECRET_DATABASE_DB: ${{ secrets.K8S_SECRET_DATABASE_DB_STABLE }}
          K8S_SECRET_DATABASE_USERNAME: ${{ secrets.K8S_SECRET_DATABASE_USERNAME_STABLE }}
          K8S_SECRET_DATABASE_PASSWORD: ${{ secrets.K8S_SECRET_DATABASE_PASSWORD_STABLE }}
          K8S_SECRET_KUKKUU_UI_BASE_URL: "https://kummilapset.hel.fi"
          K8S_SECRET_KUKKUU_NOTIFICATIONS_SHEET_ID: ${{ secrets.KUKKUU_NOTIFICATIONS_SHEET_ID }}
          K8S_SECRET_KUKKUU_HASHID_SALT: ${{ secrets.K8S_SECRET_KUKKUU_HASHID_SALT }}
          K8S_SECRET_KUKKUU_TICKET_VERIFICATION_URL: https://kummilapset-admin.hel.fi/check-ticket-validity/{reference_id}

      - name: Deploy send mail cronjob
        uses: City-of-Helsinki/setup-cronjob-action@main
        with:
          name: send-mail-cronjob
          image_repository: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
          image_tag:  ${{ github.sha }}
          kubeconfig_raw: ${{ env.KUBECONFIG_RAW }}
          target_namespace: ${{ secrets.K8S_NAMESPACE_STABLE }}
          schedule: "* * * * *" # every min
          secret_name: "project-kukkuu-secret"
          command: "{/bin/sh}"
          args: "{-c,cd /app && python manage.py send_mail}"
          max_duration: 3600 # 1h

      - name: Deploy retry deferred mails cronjob
        uses: City-of-Helsinki/setup-cronjob-action@main
        with:
          name: retry-deferred-cronjob
          image_repository: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
          image_tag:  ${{ github.sha }}
          kubeconfig_raw: ${{ env.KUBECONFIG_RAW }}
          target_namespace: ${{ secrets.K8S_NAMESPACE_STABLE }}
          schedule: "*/20 * * * *" # every 20 mins
          secret_name: "project-kukkuu-secret"
          command: "{/bin/sh}"
          args: "{-c,cd /app && python manage.py retry_deferred}"
          max_duration: 3600 # 1h

      - name: Deploy send reminder notifications cronjob
        uses: City-of-Helsinki/setup-cronjob-action@main
        with:
          name: send-reminder-notifications-cronjob
          image_repository: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
          image_tag:  ${{ github.sha }}
          kubeconfig_raw: ${{ env.KUBECONFIG_RAW }}
          target_namespace: ${{ secrets.K8S_NAMESPACE_STABLE }}
          schedule: "0 12 * * *" # daily at noon UTC
          secret_name: "project-kukkuu-secret"
          command: "{/bin/sh}"
          args: "{-c,cd /app && python manage.py send_reminder_notifications}"

      - name: Deploy send feedback notifications cronjob
        uses: City-of-Helsinki/setup-cronjob-action@main
        with:
          name: send-feedback-notifications-cronjob
          image_repository: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
          image_tag:  ${{ github.sha }}
          kubeconfig_raw: ${{ env.KUBECONFIG_RAW }}
          target_namespace: ${{ secrets.K8S_NAMESPACE_STABLE }}
          schedule: "1-59/15 * * * *" # xx:01, xx:16, xx:31, xx:46
          secret_name: "project-kukkuu-secret"
          command: "{/bin/sh}"
          args: "{-c,cd /app && python manage.py send_feedback_notifications}"
